"""add subscription pricing and invoicing

Revision ID: 09df0499fbaa
Revises: d5e4d820e7d9
Create Date: 2026-08-30 14:43:39.012465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09df0499fbaa'
down_revision: Union[str, Sequence[str], None] = 'd5e4d820e7d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_tiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('main_plan', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("main_plan IN ('BASIC', 'PRO')", name='ck_subscription_plans_main_plan'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscription_plans_active', 'subscription_plans', ['is_active'], unique=False)
    op.create_index('ix_subscription_plans_main_plan', 'subscription_plans', ['main_plan'], unique=False)
    op.create_table('client_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=False),
    sa.Column('city_tier_id', sa.Integer(), nullable=False),
    sa.Column('main_plan', sa.String(length=20), nullable=False),
    sa.Column('subscription_name', sa.String(length=150), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('price_before_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default='18', nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("billing_cycle IN ('monthly', 'annual')", name='ck_client_subscriptions_billing_cycle'),
    sa.CheckConstraint("main_plan IN ('BASIC', 'PRO')", name='ck_client_subscriptions_main_plan'),
    sa.CheckConstraint("status IN ('ACTIVE', 'EXPIRED', 'CANCELLED', 'PENDING')", name='ck_client_subscriptions_status'),
    sa.CheckConstraint('end_date > start_date', name='ck_client_subscriptions_date_order'),
    sa.CheckConstraint('price_before_tax >= 0', name='ck_client_subscriptions_price_nonnegative'),
    sa.CheckConstraint('tax_amount >= 0', name='ck_client_subscriptions_tax_nonnegative'),
    sa.CheckConstraint('tax_rate >= 0', name='ck_client_subscriptions_tax_rate_nonnegative'),
    sa.CheckConstraint('total_amount >= 0', name='ck_client_subscriptions_total_nonnegative'),
    sa.ForeignKeyConstraint(['city_tier_id'], ['city_tiers.id'], name='fk_client_subscriptions_city_tier', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='fk_client_subscriptions_client', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], name='fk_client_subscriptions_plan', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_client_subscriptions_city_tier', 'client_subscriptions', ['city_tier_id'], unique=False)
    op.create_index('ix_client_subscriptions_client', 'client_subscriptions', ['client_id'], unique=False)
    op.create_index('ix_client_subscriptions_end_date', 'client_subscriptions', ['end_date'], unique=False)
    op.create_index('ix_client_subscriptions_plan', 'client_subscriptions', ['subscription_plan_id'], unique=False)
    op.create_index('ix_client_subscriptions_status', 'client_subscriptions', ['status'], unique=False)
    op.create_table('subscription_plan_modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(length=100), nullable=False),
    sa.Column('module_name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], name='fk_subscription_plan_modules_plan', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscription_plan_modules_module_key', 'subscription_plan_modules', ['module_key'], unique=False)
    op.create_index('ix_subscription_plan_modules_plan', 'subscription_plan_modules', ['subscription_plan_id'], unique=False)
    op.create_index('uq_subscription_plan_modules_plan_module', 'subscription_plan_modules', ['subscription_plan_id', 'module_key'], unique=True)
    op.create_table('subscription_plan_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=False),
    sa.Column('city_tier_id', sa.Integer(), nullable=False),
    sa.Column('monthly_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('annual_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('annual_price >= 0', name='ck_subscription_plan_prices_annual_nonnegative'),
    sa.CheckConstraint('monthly_price >= 0', name='ck_subscription_plan_prices_monthly_nonnegative'),
    sa.ForeignKeyConstraint(['city_tier_id'], ['city_tiers.id'], name='fk_subscription_plan_prices_city_tier', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], name='fk_subscription_plan_prices_plan', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscription_plan_prices_city_tier', 'subscription_plan_prices', ['city_tier_id'], unique=False)
    op.create_index('uq_subscription_plan_prices_plan_tier', 'subscription_plan_prices', ['subscription_plan_id', 'city_tier_id'], unique=True)
    op.create_table('client_subscription_modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_subscription_id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(length=100), nullable=False),
    sa.Column('module_name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['client_subscription_id'], ['client_subscriptions.id'], name='fk_client_subscription_modules_subscription', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_client_subscription_modules_subscription', 'client_subscription_modules', ['client_subscription_id'], unique=False)
    op.create_index('uq_client_subscription_modules_subscription_module', 'client_subscription_modules', ['client_subscription_id', 'module_key'], unique=True)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('client_subscription_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='ISSUED', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default='18', nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'ISSUED', 'PAID', 'VOID', 'OVERDUE')", name='ck_invoices_status'),
    sa.CheckConstraint('subtotal >= 0', name='ck_invoices_subtotal_nonnegative'),
    sa.CheckConstraint('tax_amount >= 0', name='ck_invoices_tax_nonnegative'),
    sa.CheckConstraint('tax_rate >= 0', name='ck_invoices_tax_rate_nonnegative'),
    sa.CheckConstraint('total_amount >= 0', name='ck_invoices_total_nonnegative'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='fk_invoices_client', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_subscription_id'], ['client_subscriptions.id'], name='fk_invoices_client_subscription', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index('ix_invoices_client', 'invoices', ['client_id'], unique=False)
    op.create_index('ix_invoices_date', 'invoices', ['invoice_date'], unique=False)
    op.create_index('ix_invoices_subscription', 'invoices', ['client_subscription_id'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), server_default='1', nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_invoice_line_items_amount_nonnegative'),
    sa.CheckConstraint('quantity > 0', name='ck_invoice_line_items_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_invoice_line_items_unit_price_nonnegative'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='fk_invoice_line_items_invoice', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoice_line_items_invoice', 'invoice_line_items', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoice_line_items_invoice', table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index('ix_invoices_subscription', table_name='invoices')
    op.drop_index('ix_invoices_date', table_name='invoices')
    op.drop_index('ix_invoices_client', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('uq_client_subscription_modules_subscription_module', table_name='client_subscription_modules')
    op.drop_index('ix_client_subscription_modules_subscription', table_name='client_subscription_modules')
    op.drop_table('client_subscription_modules')
    op.drop_index('uq_subscription_plan_prices_plan_tier', table_name='subscription_plan_prices')
    op.drop_index('ix_subscription_plan_prices_city_tier', table_name='subscription_plan_prices')
    op.drop_table('subscription_plan_prices')
    op.drop_index('uq_subscription_plan_modules_plan_module', table_name='subscription_plan_modules')
    op.drop_index('ix_subscription_plan_modules_plan', table_name='subscription_plan_modules')
    op.drop_index('ix_subscription_plan_modules_module_key', table_name='subscription_plan_modules')
    op.drop_table('subscription_plan_modules')
    op.drop_index('ix_client_subscriptions_status', table_name='client_subscriptions')
    op.drop_index('ix_client_subscriptions_plan', table_name='client_subscriptions')
    op.drop_index('ix_client_subscriptions_end_date', table_name='client_subscriptions')
    op.drop_index('ix_client_subscriptions_client', table_name='client_subscriptions')
    op.drop_index('ix_client_subscriptions_city_tier', table_name='client_subscriptions')
    op.drop_table('client_subscriptions')
    op.drop_index('ix_subscription_plans_main_plan', table_name='subscription_plans')
    op.drop_index('ix_subscription_plans_active', table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_table('city_tiers')
    # ### end Alembic commands ###
