"""add client logo url

Revision ID: 1da0e1c88867
Revises: cfbd3d37fda6
Create Date: 2026-08-22 12:18:40.994355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da0e1c88867'
down_revision: Union[str, Sequence[str], None] = 'cfbd3d37fda6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.drop_constraint(op.f('uq_platform_auth_transactions_state_hash'), 'platform_auth_transactions', type_='unique')
    op.create_index('uq_platform_auth_transactions_state_hash', 'platform_auth_transactions', ['state_hash'], unique=True)
    op.drop_constraint(op.f('uq_platform_sessions_token_hash'), 'platform_sessions', type_='unique')
    op.create_index('uq_platform_sessions_token_hash', 'platform_sessions', ['session_token_hash'], unique=True)
    op.drop_constraint(op.f('uq_platform_users_identity'), 'platform_users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_platform_users_identity'), 'platform_users', ['identity_provider', 'external_subject'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_platform_sessions_token_hash', table_name='platform_sessions')
    op.create_unique_constraint(op.f('uq_platform_sessions_token_hash'), 'platform_sessions', ['session_token_hash'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_platform_auth_transactions_state_hash', table_name='platform_auth_transactions')
    op.create_unique_constraint(op.f('uq_platform_auth_transactions_state_hash'), 'platform_auth_transactions', ['state_hash'], postgresql_nulls_not_distinct=False)
    op.drop_column('clients', 'logo_url')
    # ### end Alembic commands ###
