"""create clients table

Revision ID: 20b71c73cf12
Revises: 
Create Date: 2026-08-09 09:19:54.681080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b71c73cf12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('legal_business_name', sa.String(length=250), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('business_email', sa.String(length=255), nullable=False),
    sa.Column('business_phone', sa.String(length=30), nullable=False),
    sa.Column('owner_name', sa.String(length=200), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=False),
    sa.Column('owner_phone', sa.String(length=30), nullable=False),
    sa.Column('owner_role', sa.String(length=50), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('billing_cycle', sa.String(length=30), nullable=False),
    sa.Column('subscription_status', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###
