"""add firebase provisioning fields

Revision ID: 2a0bb626695d
Revises: b55564cab1b9
Create Date: 2026-08-09 10:46:12.544569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a0bb626695d'
down_revision: Union[str, Sequence[str], None] = 'b55564cab1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "clients",
        sa.Column(
            "firebase_project_id",
            sa.String(length=100),
            nullable=True,
        ),
    )

    op.add_column(
        "clients",
        sa.Column(
            "firebase_provisioning_status",
            sa.String(length=30),
            nullable=True,
        ),
    )

    op.add_column(
        "clients",
        sa.Column(
            "firebase_provisioned_at",
            sa.DateTime(),
            nullable=True,
        ),
    )

    op.execute(
        """
        UPDATE clients
        SET firebase_provisioning_status = 'PENDING'
        WHERE firebase_provisioning_status IS NULL
        """
    )

    op.alter_column(
        "clients",
        "firebase_provisioning_status",
        existing_type=sa.String(length=30),
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'firebase_provisioned_at')
    op.drop_column('clients', 'firebase_provisioning_status')
    op.drop_column('clients', 'firebase_project_id')
    # ### end Alembic commands ###
