"""add firebase provisioning error

Revision ID: 463e00e45ae0
Revises: 2a0bb626695d
Create Date: 2026-08-11 16:25:50.932161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463e00e45ae0'
down_revision: Union[str, Sequence[str], None] = '2a0bb626695d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('firebase_provisioning_error', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'firebase_provisioning_error')
    # ### end Alembic commands ###
