"""align tenant id index

Revision ID: b55564cab1b9
Revises: 0a4fd6316d72
Create Date: 2026-08-09 10:03:26.050947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55564cab1b9'
down_revision: Union[str, Sequence[str], None] = '0a4fd6316d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_clients_tenant_id'), 'clients', type_='unique')
    op.create_index(op.f('ix_clients_tenant_id'), 'clients', ['tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_tenant_id'), table_name='clients')
    op.create_unique_constraint(op.f('uq_clients_tenant_id'), 'clients', ['tenant_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
