"""add client crm domain

Revision ID: d5e4d820e7d9
Revises: 1da0e1c88867
Create Date: 2026-08-22 19:52:18.175892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e4d820e7d9'
down_revision: Union[str, Sequence[str], None] = '1da0e1c88867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('crm_domain', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_clients_crm_domain'), 'clients', ['crm_domain'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_crm_domain'), table_name='clients')
    op.drop_column('clients', 'crm_domain')
    # ### end Alembic commands ###
